name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # jalan tiap hari
  workflow_dispatch: # bisa dijalankan manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman graph
        uses: yoshi389111/github-contribution-graph-action@v1.0.7
        with:
          user_name: RofiFadlurrahman
          mode: pacman

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./output
